#ifndef __ADDON_CALLBACKS_H__
#define __ADDON_CALLBACKS_H__

#include <node.h>

// NOTE: This header is generated by the Go build.
#include "../lib/libgo.h"

struct fn_state_t {
  v8::Isolate *isolate;

  // XXX: Hack context until proper management is figured out...
  const v8::FunctionCallbackInfo<v8::Value> *cb;
  // v8::ReturnValue<v8::Value> rv;
};

struct fn_state_t *AllocState(
  const v8::FunctionCallbackInfo<v8::Value> &cb
);

void FreeState(struct fn_state_t *state);

struct fn_callbacks_t GetCallbacks();

#endif /* __ADDON_CALLBACKS_H__ */
