#ifndef __ADDON_VALUE_H__
#define __ADDON_VALUE_H__

#include <node.h>

// NOTE: This header is generated by the Go build.
#include "../lib/libgo.h"

size_t GetNumArgs(
  const v8::FunctionCallbackInfo<v8::Value> &cb
);

struct array_t *AllocArgs(
  const v8::FunctionCallbackInfo<v8::Value> &cb
);

void FreeArgs(struct array_t *args);

#endif /* __ADDON_VALUE_H__ */
